# --------------------------------------------------
# Configuration for testing / evaluation with ground truth
# --------------------------------------------------

project:
  seed: 42
  device: cuda                  # Use "cuda" for GPU, or "cpu" for CPU

paths:
  dataset: ./datasets/dataset_test1 # Path to dataset used for evaluation
  output_root: ./output
  checkpoint_path: ./output/training/2026-07-12_01-50-35/dataset_val/best_model_resnet34_dataset_val.pth

model:
  backbone: resnet34            # Selected backbone model. The backbone must match the one used during training of the checkpoint!

  backbones:                    # Available backbone architectures (VRAM requirements depend on the backbone)
    resnet18:
      base: 16                  # Base channel width; controls model width (higher = more channels)
    resnet34:
      base: 16
    resnet50:
      base: 64
    wide_resnet50_2:
      base: 64

thresholds:
  image_quantile:  0.99         # Sets a threshold so that a chosen percentage of pixel anomaly scores lies below it, reducing the impact of isolated extreme values
  image_threshold: 0.66         # Threshold applied to the image-level anomaly score for classification
  pixel_threshold: 0.72         # Pixel is considered anomalous above this score
  min_region_area: 6500         # Removes connected regions smaller than this area (noise filtering)

polygon:
  polygon_epsilon_ratio: 0.004  # Controls polygon simplification (higher = fewer points, larger spacing)

morphology:
  enabled: true                 # Enable/disable morphological mask cleanup
  kernel_size: 3                # Neighborhood size (3×3) used to suppress noise
  open_iterations: 0            # Strength of noise removal and mask smoothing
  close_iterations: 50          # Strength of hole filling

dataset:
  image_size: 256


